export const baselineTour = [
  // {
  //   title: "Let's start the product tour.",
  //   content: 'Click Next to begin.',
  //   placement: 'center',
  //   target: 'body',
  // },
  // {
  //   title: 'Your Assessment Cycle',
  //   content: 'Your Assessment Cycle',
  //   spotlightPadding: 20,
  //   target: '.asc',
  //   disableBeacon: true,
  // },
  {
    title: 'Simulation Tutorial Button',
    content: 'Simulation Tutorial Button',
    spotlightPadding: 20,
    target: '.simTutorial',
    disableBeacon: true,
  },
  {
    title: 'Due date',
    content: 'Due date',
    spotlightPadding: 20,
    target: '.dueDate',
    disableBeacon: true,
  },
  {
    title: 'Baseline',
    content: 'Your Baseline',
    spotlightPadding: 20,
    target: '.baseline',
    disableBeacon: true,
  },
  {
    title: 'Trainings',
    content: 'Your Trainings',
    spotlightPadding: 10,
    target: '.training',
    disableBeacon: true,
  },
  {
    title: 'Followups',
    content: 'Your Followups',
    spotlightPadding: 10,
    target: '.followup',
    disableBeacon: true,
  },
  {
    title: 'Instructions',
    content: 'Instructions',
    spotlightPadding: 10,
    target: '.instruction',
    disableBeacon: true,
  },
  {
    title: 'Protocols',
    content: 'Protocols',
    spotlightPadding: 10,
    target: '.protocol',
    disableBeacon: true,
  },
  {
    title: 'Study Documents',
    content: 'Study Documents',
    spotlightPadding: 10,
    target: '.studydoc',
    disableBeacon: true,
  },
  {
    title: 'Date info',
    content: 'Date info',
    spotlightPadding: 10,
    target: '.date',
    disableBeacon: true,
  },
  {
    title: 'Time info',
    content: 'Time info',
    spotlightPadding: 10,
    target: '.time',
    disableBeacon: true,
  },
  {
    title: 'Status',
    content: 'Status',
    spotlightPadding: 10,
    target: '.status',
    disableBeacon: true,
  },
  {
    title: 'Session count',
    content: 'Session count',
    spotlightPadding: 20,
    target: '.count',
    disableBeacon: true,
  },
  {
    title: 'Start button',
    content: 'Start button',
    spotlightPadding: 20,
    target: '.start',
    disableBeacon: true,
  },
];

export const trainingTour = [
  //   {
  //     title: 'View Result',
  //     content: 'View Result',
  //     spotlightPadding: 20,
  //     target: '.result',
  //   },
  {
    title: 'Trainings',
    content: 'Trainings',
    spotlightPadding: 20,
    target: '.trainings',
    disableBeacon: true,
  },
  {
    title: 'Training Tutorial',
    content: 'Training Tutorial',
    spotlightPadding: 20,
    target: '.trainingTutorial',
    disableBeacon: true,
  },
  {
    title: 'Domain',
    content: 'Domain',
    spotlightPadding: 20,
    target: '.domain',
    disableBeacon: true,
  },
  {
    title: 'Training Progress',
    content: 'Training Progress',
    spotlightPadding: 20,
    target: '.progress',
    disableBeacon: true,
  },
  {
    title: 'Training Duration',
    content: 'Training Duration',
    spotlightPadding: 20,
    target: '.duration',
    disableBeacon: true,
  },
  {
    title: 'Training Status',
    content: 'Training Status',
    spotlightPadding: 20,
    target: '.tstatus',
    disableBeacon: true,
  },
  {
    title: 'Training button',
    content: 'Training button',
    spotlightPadding: 20,
    target: '.trainingBtn',
    disableBeacon: true,
  },
  {
    title: 'Followups',
    content: 'Followups',
    spotlightPadding: 20,
    target: '.followups',
    disableBeacon: true,
  },
];

export const viewportTour = [
  {
    title: 'Home button',
    content: 'Home button',
    spotlightPadding: 20,
    target: '.home',
    disableBeacon: true,
  },
  {
    title: 'Add viewport',
    content: 'Add viewport',
    spotlightPadding: 20,
    target: '.addV',
    disableBeacon: true,
  },
  {
    title: 'Instructions',
    content: 'Instructions',
    spotlightPadding: 20,
    target: '.instructions',
    disableBeacon: true,
  },
  {
    title: 'Session Count',
    content: 'Session Count',
    spotlightPadding: 20,
    target: '.ac',
    disableBeacon: true,
  },
  {
    title: 'Submit button',
    content: 'Submit button',
    spotlightPadding: 20,
    target: '.submit',
    disableBeacon: true,
  },
  {
    title: 'Timer',
    content: 'Timer',
    spotlightPadding: 20,
    target: '.timer',
    disableBeacon: true,
  },
  {
    title: 'Select Document',
    content: 'Select Document',
    spotlightPadding: 20,
    target: '#documents',
    // spotlightClicks: true,
    // hideCloseButton: true,
    // hideFooter: true,
    // disableOverlayClose: true,
    disableBeacon: true,
  },
  // {
  //   title: 'folder',
  //   content: 'folder',
  //   spotlightPadding: 20,
  //   target: '#folder',
  //   disableBeacon: true,
  //   spotlightClicks: true,
  //   hideCloseButton: true,
  //   hideFooter: true,
  // },
  // {
  //   title: 'document',
  //   content: 'document',
  //   spotlightPadding: 20,
  //   target: '#document',
  //   disableBeacon: true,
  // },
  // {
  //   title: 'note',
  //   content: 'note',
  //   spotlightPadding: 20,
  //   target: '.note',
  //   disableBeacon: true,
  // },
];
